name: Sync Releases from Upstream

on:
  release:
    types: [published]
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download assets from upstream release
      run: |
        curl -L -o assets.zip "https://github.com/netbirdio/netbird/releases/download/${UPSTREAM_RELEASE_TAG}/${{ github.event.release.name }}.zip"
        # 解压 assets.zip 到一个临时目录

    - name: Create a new release in the fork
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.name }}
        body: ${{ github.event.release.body }}
        draft: false
        prerelease: ${{ github.event.release.prerelease }}

    - name: Upload assets to the new release
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary "@assets.zip" "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/${{ github.event.release.id }}/assets?name=${{ github.event.release.name }}.zip"
